# spring ???
spring:

  # ?? ??? ?? ( ??? ????? ??? ?? )
  time-zone: Asia/Seoul

  # DB ??
  datasource:
    url: jdbc:mysql://localhost:3306/jmarket
    username: root
    password: aod37988##
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa ??
  jpa:
    hibernate:
      ddl-auto: update # ??? ?? ??? update ? ?? ??
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    security:
      enable-csrf: false